global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.chaincart.com:9443"]
  - job_name: "peer0_platform"
    static_configs:
      - targets: ["peer0.platform.chaincart.com:9444"]
  - job_name: "peer0_flipkart"
    static_configs:
      - targets: ["peer0.flipkart.chaincart.com:9445"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
