#!/bin/bash

function createPlatform() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/platform.chaincart.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/platform.chaincart.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-platform --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-platform.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-platform.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-platform.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-platform.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy platform's CA cert to platform's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/tlscacerts/ca.crt"

  # Copy platform's CA cert to platform's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/tlsca/tlsca.platform.chaincart.com-cert.pem"

  # Copy platform's CA cert to platform's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.chaincart.com/ca"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/ca/ca.platform.chaincart.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-platform --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-platform --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-platform --id.name platformadmin --id.secret platformadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls" --enrollment.profile tls --csr.hosts peer0.platform.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/platform.chaincart.com/peers/peer0.platform.chaincart.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.chaincart.com/users/User1@platform.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/users/User1@platform.chaincart.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://platformadmin:platformadminpw@localhost:7054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.chaincart.com/users/Admin@platform.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.chaincart.com/users/Admin@platform.chaincart.com/msp/config.yaml"
}

function createFlipkart() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/flipkart.chaincart.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-flipkart --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-flipkart.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-flipkart.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-flipkart.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-flipkart.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy flipkart's CA cert to flipkart's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/tlscacerts/ca.crt"

  # Copy flipkart's CA cert to flipkart's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/tlsca/tlsca.flipkart.chaincart.com-cert.pem"

  # Copy flipkart's CA cert to flipkart's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/ca"
  cp "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/ca/ca.flipkart.chaincart.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-flipkart --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-flipkart --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-flipkart --id.name flipkartadmin --id.secret flipkartadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-flipkart -M "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-flipkart -M "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls" --enrollment.profile tls --csr.hosts peer0.flipkart.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/peers/peer0.flipkart.chaincart.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-flipkart -M "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/users/User1@flipkart.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/users/User1@flipkart.chaincart.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://flipkartadmin:flipkartadminpw@localhost:8054 --caname ca-flipkart -M "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/users/Admin@flipkart.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/flipkart/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/flipkart.chaincart.com/users/Admin@flipkart.chaincart.com/msp/config.yaml"
}

function createAmazon() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/amazon.chaincart.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/amazon.chaincart.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11154 --caname ca-amazon --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11154-ca-amazon.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11154-ca-amazon.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11154-ca-amazon.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11154-ca-amazon.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy amazon's CA cert to amazon's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/tlscacerts/ca.crt"

  # Copy amazon's CA cert to amazon's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/tlsca/tlsca.amazon.chaincart.com-cert.pem"

  # Copy amazon's CA cert to amazon's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/ca"
  cp "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/ca/ca.amazon.chaincart.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-amazon --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-amazon --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-amazon --id.name amazonadmin --id.secret amazonadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11154 --caname ca-amazon -M "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11154 --caname ca-amazon -M "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls" --enrollment.profile tls --csr.hosts peer0.amazon.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/peers/peer0.amazon.chaincart.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11154 --caname ca-amazon -M "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/users/User1@amazon.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/users/User1@amazon.chaincart.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://amazonadmin:amazonadminpw@localhost:11154 --caname ca-amazon -M "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/users/Admin@amazon.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/amazon/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/amazon.chaincart.com/users/Admin@amazon.chaincart.com/msp/config.yaml"
}

function createMyntra() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/myntra.chaincart.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/myntra.chaincart.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-myntra --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-myntra.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-myntra.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-myntra.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-myntra.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy myntra's CA cert to myntra's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/tlscacerts/ca.crt"

  # Copy myntra's CA cert to myntra's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/tlsca/tlsca.myntra.chaincart.com-cert.pem"

  # Copy myntra's CA cert to myntra's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/ca"
  cp "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/ca/ca.myntra.chaincart.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-myntra --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-myntra --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-myntra --id.name myntraadmin --id.secret myntraadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-myntra -M "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-myntra -M "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls" --enrollment.profile tls --csr.hosts peer0.myntra.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/peers/peer0.myntra.chaincart.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-myntra -M "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/users/User1@myntra.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/users/User1@myntra.chaincart.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://myntraadmin:myntraadminpw@localhost:10054 --caname ca-myntra -M "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/users/Admin@myntra.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/myntra/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/myntra.chaincart.com/users/Admin@myntra.chaincart.com/msp/config.yaml"
}

function createTataneu() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/tataneu.chaincart.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-tataneu --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-tataneu.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-tataneu.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-tataneu.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-tataneu.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy tataneu's CA cert to tataneu's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/tlscacerts/ca.crt"

  # Copy tataneu's CA cert to tataneu's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/tlsca/tlsca.tataneu.chaincart.com-cert.pem"

  # Copy tataneu's CA cert to tataneu's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/ca"
  cp "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/ca/ca.tataneu.chaincart.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-tataneu --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-tataneu --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-tataneu --id.name tataneuadmin --id.secret tataneuadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-tataneu -M "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-tataneu -M "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls" --enrollment.profile tls --csr.hosts peer0.tataneu.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/peers/peer0.tataneu.chaincart.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-tataneu -M "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/users/User1@tataneu.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/users/User1@tataneu.chaincart.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://tataneuadmin:tataneuadminpw@localhost:11054 --caname ca-tataneu -M "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/users/Admin@tataneu.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/tataneu/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/tataneu.chaincart.com/users/Admin@tataneu.chaincart.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/chaincart.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/chaincart.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/chaincart.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/chaincart.com/msp/tlscacerts/tlsca.chaincart.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/chaincart.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/chaincart.com/tlsca/tlsca.chaincart.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls" --enrollment.profile tls --csr.hosts orderer.chaincart.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/chaincart.com/orderers/orderer.chaincart.com/msp/tlscacerts/tlsca.chaincart.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/chaincart.com/users/Admin@chaincart.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/chaincart.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/chaincart.com/users/Admin@chaincart.com/msp/config.yaml"
}
