# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Amazon
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: AmazonMSP

        # ID to load the MSP definition as
        ID: AmazonMSP

        MSPDir: ../organizations/peerOrganizations/amazon.chaincart.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AmazonMSP.admin', 'AmazonMSP.peer', 'AmazonMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AmazonMSP.admin', 'AmazonMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AmazonMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AmazonMSP.peer')"
